name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm ci

      - name: Lint avec ESLint
        run: npm run lint
        
      - name: Exécuter les tests unitaires avec Jest
        run: npm test
